services:
  db:
    build: ./db
    container_name: bank-mssql
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA}"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "${MSSQL_PID}"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - banknet

  backend:
    build: ./backend
    container_name: bank-backend
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
      PORT: "${PORT}"
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - banknet

  frontend:
    image: nginx:latest
    container_name: bank-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - banknet

volumes:
  mssql-data:

networks:
  banknet:
